{% set name = "cachetools" %}
{% set version = "7.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1a7537025c06abf96fcc1443e496af9a3fb95e774e70e1f0af226f73f7f2dcc

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=80
    - setuptools-scm >=8.2
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - cachetools
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/tkem/cachetools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extensible memoizing collections and decorators
  description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
  doc_url: https://pypi.org/project/cachetools/
  dev_url: https://github.com/tkem/cachetools

extra:
  recipe-maintainers:
    - maartenbreddels
    - marcelotrevisani
