{% set name = "cachetools" %}
{% set version = "6.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e6d266b25e539df852251cfd6f990b4bc3a141db73b939058d809ebd2590fc6

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - cachetools
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/tkem/cachetools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extensible memoizing collections and decorators
  description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
  doc_url: https://pypi.org/project/cachetools/
  dev_url: https://github.com/tkem/cachetools

extra:
  recipe-maintainers:
    - maartenbreddels
    - marcelotrevisani
