travis:
  secure:
    BINSTAR_TOKEN: yEtEIGagFrGYzD7xm0VLZjkZ7Xz5LmGTvdvL1r1S01NagnCinNVNnc3hUR+kTMDvvZKBixo+2rzOAAzL2MxRTX5FEB1PwmvoBkKCjf8datglqLjs3ZEcapF8OyckP9HAYAIhaOX6RCxN32U0u6Vz2rg8Zwhu3GqeEyiMS4WF9wLMvP+b60lLT2vFIOBSwIwDTOWD3dux5hF2yo8gMZReuxUWX6BV39keBrZKSJH9UCAj2S6b/kD4oJWJUApgSUj82D0mWLBctgWZ/ZpA0tXuBZyJwssN6r+R/Vjwnf90xMHYqOkl0oxs9qFgpS7RVkx7GGo4twlY5FIFXXnUyhzy/2exHHpcBVpqNeX2A+yBX4/r93Ryk7BCz9D+Rh1SVdgnLF97FUPheQm8qVZZumtrNDd2XabkaCTPgK7QP31B8w3PnoB596i/UYCySu8XviIPssx9olXOU2aS3NDR0mTmraXkuiiNIAnzBRyPcIy7+2oJlX17V+42aUcj9WSuPFnOI1UFnlSLt6JaViDYLLaXIBMs+uZkRgx+uTdOZO87np064ZGA680njwmMNMBq03+VWuZe/jx9j/0b4eqHJtRWBb5UglX83oBCvPtnSl3hUxAFrOdInEddjW3pM+gq6PJf1p8lvX8eFX27NBDGWadQRQk1q64mOd4VeH8sujNRNSk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
