travis:
  secure:
    BINSTAR_TOKEN: zoGJs7nS0Uwhx+HGoGY7gu/A2+emrIDx/SKga0WFKfwT6AJ1Cn9kUBX1vWjf3m77jrQ8acvaajD4ghIsM0zI+lA/IP3/6UyJbj3R9jR9+Uq3kzLiHlJ7+qGiK7SrtABZpr8i/JPZN/bxvFXmOIaXSp6JTRML8Rx+PjaMIpUFUHoJLC+jNwQv6fOphwobK9miyq17loy2KMLPuNj+tDsp7QZXoygKofXmZ6c8IWiVGM7VWBcuKwlkK6X3hZ0WGC39i7+CYPdXC1k5+tY1+8f0vqWx4zcv5kEJWZBgRZXVO8/jreTHputsseQ4vQfeXGe0gvsGFDLDtLXYOxZdj4tiD44lACUlZfTfGIKR/usCqjeHXEcNDrqojfSBdCCsx/Eh7DhrPdi4rofetIdaqQ1Z0OkIhZXer3pBQ/rBmdCZdj3wslqscz8GcB/ShVvjyNHaJAF7OUP04D5hXIlO+Ng3CgUth3nkTnywEsRfB+iz5zk8lAusgJ0mUc+nTs30VBpTVcQMx+nmh9osJ6rZNYDUcj/5w8vlKyMD6HtmDptzJG+w2b5JibURJRjN0k22mu1VlbBoUJrOcXDusHh2Dl8AFmAZe3HN6pW38HFhHdWRksjP6nf0e6AWsJP9Nns8lXDjzNHUbDF9BpsROnoZ5iwZQXYJ3d6JI/O3TFbiI9KDxW8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
