travis:
  secure:
    BINSTAR_TOKEN: kQZaZDLekjA9NONMmujS8haZ69iAHyOok5gIACnCj9+UDk7DIylj+c8TqSFlwEJqB5XtzlfsCR39sRNwvZUMXfFZEDblvlODGvzA7GP5nBsed531rUWiZSOW6PSAY2fpexjxxOAy5fbukzdcKPKHMZtI9hcIgOS6BdS7ZZyVhxOzxlwt9c4shSXTqTQKHZbh+BWdmin1FoDIxEuvO2ddZiS6Q6wcvQlrQIvs8Jq5+qNTCRfrUC5sbRenrSFSWQzJ/pMJumyxJ9REiBKHJUdTAuYvGdrx7j1nbGxZjSojM6F2I0rYC90IhNu2rYWpEt8jYVx7SiF4kfoXQIYOHRa4a+9fDtnTCAultCXZSAQm5bgWNx3urNj7ASOz76Fa0hcj3RaBwbC0Jj6F3JtNPaf8pcsAlZnWKyhrbqH2V7O+9PrTJWfsCvmKaJItVYfVo2KdpI7zuEHcB9H+b5KE2AoI251G/ilXR0p/tCOCZoS63KalzvbRG3sGRRjGQ/eKw2e/nexhoNm+QbVpz2NZO4J7nW5YVw2bX3In+PNKphilazICavVJpqq3Xie6PfP7EsMT2C36r0o+b0w446aqjtQzxMFTQ7rQHMXgGOiyIsGCYUiKoyqzRcWmnNHkkWrmvvGUZdVBXrxf3HFLQ72YgA7y66VgRpWrc3Cc6AdFt0frbhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
